apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
  namespace: kong
data:
  game.properties: |-
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
