apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: kong
spec:
  replicas: 1
  selector:
   matchLabels:
    app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: papawhiskey93/nodeapp:1.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
